### ISSUE TITLE
nested rule with dynamic value doesnt seem to work

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#445]
@xiaofan2406 commented on [Fri Mar 17 2017](https://github.com/cssinjs/react-jss/issues/76)

```
container: {
    color: props => props.color, // this works
    '&:before' : {
        content: 'text',
        color: props => props.color // this doesn't
    }
}
```

Did i miss something?

---

@kof commented on [Fri Mar 17 2017](https://github.com/cssinjs/react-jss/issues/76#issuecomment-287322541)

Yeah, works right now only for top level rules. Lets keep this issue for enhancement. Not sure though if it is worth it.

**Comment by jcheroske** [comment]
I would love to see this feature.

**Comment by kof** [comment]
Feel free to take a deeper look and send a pr if you can.

**Comment by PolGuixe** [comment]
I would love to see this implemented I am trying to build a grid system with JSS and I feel I really need dynamic values in nested rules.

**Comment by xiaofan2406** [comment]
@kof Can you please suggest any temporary workaround for this issue?

**Comment by kof** [comment]
Workaround would be to not to use nested rules with function values right now. Will be fixed soon.

**Comment by PolGuixe** [comment]
@kof When you reckon that it would be available?

**Comment by kof** [comment]
today) part of #444

**Comment by kof** [comment]
Fixed, check out jss 7.0

**Comment by xiaofan2406** [comment]
Not sure if I missed anything, but it doesn't seem to work for me.

**Comment by kof** [comment]
Have you installed the latest  jss-nested@4.0 as well?

**Comment by xiaofan2406** [comment]
yes. I cleared `node_modules` and reinstalled as well just to be sure. Still not working.

**Comment by kof** [comment]
but did you look into the package.json of your installed jss-nested? The thing is I have  a [test](https://github.com/cssinjs/jss-nested/blob/master/src/index.test.js#L599) for this case and it works, what do you do different? Can you submit a test?

**Comment by xiaofan2406** [comment]
Alright. Turns out mixing `npm` and `yarn` can cause some weird version errors. MB, it is working as expected.
